### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by orcunhanay** [aws/porting-assistant-dotnet-ui#756] opened 2023-02-13 11:30 UTC
When a project analysis is continue, I had to close Porting Assistant. When I run it again, it stays on the white screen. If you are lucky after waiting for a while, the dashboard appears but I can see that a project is in "In Progress", but the screen is not responding because the main thread is busy.

This problem has in version 1.9.2

![Screenshot 2023-02-10 181834](https://user-images.githubusercontent.com/13981015/218445394-683a02ca-78a4-40f1-b6ce-a92b956d9de3.png)

**Comment by huawenm** [comment] 2023-02-15 20:26
Thank you for report the issue! It seems a bug in our tools, we have a ticket to track the issue internally, the team is currently investigating the root cause, will let you know once it is fixed.

**Comment by saikiranakula-amzn** [comment] 2023-02-21 16:40
This issue is similar to the issue - https://github.com/aws/porting-assistant-dotnet-ui/issues/757, which is also resolved by clearing the cache with duplicate reducer files

**Closed** 2023-03-14 13:03 UTC
